### ISSUE TITLE
makefile

### ISSUE THREAD

**Issue by shawn07023** [jinwookjungs/lefdef_util#2]
When I try to use 'make' under Linux system in the bookshelf, it return a error 'g++: fetal error: no input files'. So I checked the makefile, is it possible that we should put any dependency after $(OBJS) in line 43. Sorry, I only have a little experience in simple makefile.  Thanks

**Comment by jinwookjungs** [comment]
Can you please try `make depend && make`?

**Comment by shawn07023** [comment]
Thank you so much. It did work.
